name: plug
description: SmartPlug App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  uuid: ^4.2.1
  path: ^1.8.3
  intl: ^0.18.1
  location: ^5.0.3
  wifi_scan: ^0.4.0+2
  http_parser: ^4.0.2
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  flutter_bloc: ^8.1.3
  path_provider: ^2.1.1
  open_settings: ^2.0.2
  flutter_vibrate: ^1.3.0
  connectivity_plus: ^4.0.2
  permission_handler: ^11.0.1
  flutter_blue_plus: ^1.28.10
  flutter_screenutil: ^5.9.0

  sla_logger:
    git:
      url: https://github.com/nasirdev74/sla_logger_app
      path: package/sla_logger

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
